@base_url=localhost:4000

GET http://{{base_url}}/

###
GET http://{{base_url}}/user

###
GET http://{{base_url}}/user/farman

###
GET http://{{base_url}}/userDetails?id=123&name=farman&address=mumbai

###
POST http://{{base_url}}/add-learner
Content-Type: application/json
secret_key:admin@123456#

{
    "id":4,
    "name":"utpal",
    "address":"patna"
}

###
GET http://{{base_url}}/all-learners

###
PUT  http://{{base_url}}/update-learner/4
Content-Type: application/json
secret_key:admin@123456#

{
    "name":"khushi",
    "address":"rajasthan"
}

###
DELETE  http://{{base_url}}/delete-learner/3
secret_key:admin@123456#